# title: "Tech with Sajja’s"
# description: "DevOps, Cloud, Automation, and Career Growth"
# baseurl: ""
# url: "https://autoshiftops.com"
# theme: null
# plugins:
#   - jekyll-seo-tag
#   - jekyll-feed

theme: null
title: "AutoShiftOps"
description: "Tech with Sajja’s — DevOps, Cloud & AI simplified"
baseurl: ""
url: "https://autoshiftops.com"
markdown: kramdown
highlighter: rouge
include:
  - _pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-tagging
paginate: 2
paginate_path: "/blog/page:num"
